version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432 

    environment:
      - POSTGRES_DB=Interview
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
